name: flake8

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  linter:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    name: spell check

    steps:
      - uses: actions/checkout@main
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install flake8
        run: python -m pip install -q flake8
      - name: flake8 - check ./*py
        run: flake8 ./*py
      - name: flake8 - check processNano/*py
        run: flake8 processNano/*py
      - name: flake8 - check processNano/corrections/*py
        run: flake8 processNano/corrections/*py
      - name: flake8 - check produceResults/*py
        run: flake8 produceResults/*py
      - name: flake8 - check doAnalysis/*py
        run: flake8 doAnalysis/*py
      - name: flake8 - check config/*py
        run: flake8 config/*py
      - name: flake8 - check tests/*py
        run: flake8 tests/*py
